language: php

php:
  - 7.1
  - 7.2

os:
  - linux

sudo: false

install:
  # Composer packages
  composer install
  # Coveralls
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

# Create a storage folder for Coverage report
before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php coveralls.phar -v
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: master
